name: EMPE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  IMAGE_NAME: devops-team3
  CONTAINER_NAME: devops-team3
  REGISTRY: 10.0.40.171:5000
  SONAR_HOST_URL: http://10.0.40.165:9000
  SONAR_PROJECT_KEY: Devops-Team3-key

jobs:
  build:
    runs-on: self-hosted

    steps:

      - name: Fix workspace permissions
        run: |
          docker run --rm \
            -v "$PWD":/project \
            bash:5.2 \
            bash -c "chown -R $(id -u):$(id -g) /project"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build application
        run: |
          docker run --rm -u gradle \
            -v "$PWD:/home/gradle/project" \
            -w /home/gradle/project \
            gradle:8-jdk17-alpine \
            gradle build

      - name: SonarQube analysis
        run: |
          docker run --rm -u 1000 \
            -e SONAR_HOST_URL="$SONAR_HOST_URL" \
            -e SONAR_TOKEN="${{ secrets.SONAR_TOKEN }}" \
            -v "$PWD:/usr/src" \
            sonarsource/sonar-scanner-cli \
            -Dsonar.projectKey=$SONAR_PROJECT_KEY \
            -Dsonar.sources=src/main/java \
            -Dsonar.tests=src/test/java \
            -Dsonar.java.binaries=build/classes/java/main \
            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .

      - name: Stop and remove old container
        run: |
          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true

      - name: Start container
        run: |
          docker run -d \
            --name $CONTAINER_NAME \
            --restart unless-stopped \
            -p 8080:8080 \
            $IMAGE_NAME:latest

      - name: Integration test
        run: |
          if curl -f http://localhost:8080/hello; then
            echo "Integration test successful"
            exit 0
          fi

          echo "Endpoint not reachable yet. Waiting 10 seconds..."
          sleep 10

          if curl -f http://localhost:8080/hello; then
            echo "Integration test successful"
            exit 0
          else
            echo "Integration test failed"
            exit 1
          fi

      - name: Tag Docker image
        run: |
          docker tag $IMAGE_NAME:latest $REGISTRY/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest $REGISTRY/$IMAGE_NAME:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:latest
          docker push $REGISTRY/$IMAGE_NAME:${{ github.sha }}