name: EMPE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:

      - name: Fix workspace permissions
        run: |
          docker run --rm \
            -v "$PWD":/project \
            bash:5.2 \
            bash -c "chown -R $(id -u):$(id -g) /project"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build application
        run: |
          docker run --rm -u gradle \
            -v "$PWD:/home/gradle/project" \
            -w /home/gradle/project \
            gradle:8-jdk17-alpine \
            gradle build

      - name: Build Docker image
        run: |
          docker build -t devops-projekt:latest .

      - name: Stop and remove old container
        run: |
          docker stop devops-projekt || true
          docker rm devops-projekt || true

      - name: Start container
        run: |
          docker run -d \
            --name devops-projekt \
            --restart unless-stopped \
            -p 8080:8080 \
            devops-projekt:latest

      - name: Integration test
        run: |
          if curl -f http://localhost:8080/hello; then
            echo "Integration test successful"
            exit 0
          fi

          echo "Endpoint not reachable yet. Waiting 10 seconds..."
          sleep 10

          if curl -f http://localhost:8080/hello; then
            echo "Integration test successful"
            exit 0
          else
            echo "Integration test failed"
            exit 1
          fi

      - name: Tag Docker image
        run: |
          docker tag devops-projekt:latest \
            10.0.40.171:5000/devops-projekt:latest

      - name: Push Docker image
        run: |
          docker push 10.0.40.171:5000/devops-projekt:latest
